### PR TITLE
add NightmareFox personal page 

### PR DESCRIPTION
**Pull request by NightmareFox12**
### Desktop View:
image

### Mobile View:
[](https://github.com/user-attachments/assets/596f073e-19e2-4f08-bd8b-5c7bad4e8667)

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

### CODE REVIEW

**Review by Pabl0cks — CHANGES_REQUESTED** [review]
Thanks for the PR @NightmareFox12 !! I really like your design and how you managed the responsive 🙌

Added a few comments (a couple of errors I was getting and the rest are nitpick suggestions).

For future PRs, please ensure you create and check out a new branch (see contribution guideline, https://gist.github.com/ZakGriffith/69d1eb8baebddd7d370b87a65a7e3ec0).

Let me know if you need any help fixing the errors! 🙏

**Comment by NightmareFox12** [comment]
Thank you very much for the corrections! ✨✨

**Comment by Pabl0cks** [comment]
> Thank you very much for the corrections! ✨✨

You're welcome! 

Just FYI, next time you can just push the corrections to the same PR, and it gets updated, so you can keep the track better of what's fixed and what's not, and other people can review the same PR and have all the context 🙌

**Comment by NightmareFox12** [comment]
> > Thank you very much for the corrections! ✨✨
> 
> You're welcome!
> 
> Just FYI, next time you can just push the corrections to the same PR, and it gets updated, so you can keep the track better of what's fixed and what's not, and other people can review the same PR and have all the context 🙌

hahaha, it's my first time doing PR to a project and I closed the PR without knowing, I'm sorry 😅

**Pull request closed without merging**
